# Generated by Django 3.2.5 on 2022-11-01 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_name', models.CharField(max_length=40)),
                ('goals_scored', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('team_code', models.IntegerField()),
                ('total_points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserFplPicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1_pos', models.IntegerField()),
                ('p1_cpt', models.BooleanField()),
                ('p1_vcpt', models.BooleanField()),
                ('p2_pos', models.IntegerField()),
                ('p2_cpt', models.BooleanField()),
                ('p2_vcpt', models.BooleanField()),
                ('p3_pos', models.IntegerField()),
                ('p3_cpt', models.BooleanField()),
                ('p3_vcpt', models.BooleanField()),
                ('p4_pos', models.IntegerField()),
                ('p4_cpt', models.BooleanField()),
                ('p4_vcpt', models.BooleanField()),
                ('p5_pos', models.IntegerField()),
                ('p5_cpt', models.BooleanField()),
                ('p5_vcpt', models.BooleanField()),
                ('p6_pos', models.IntegerField()),
                ('p6_cpt', models.BooleanField()),
                ('p6_vcpt', models.BooleanField()),
                ('p7_pos', models.IntegerField()),
                ('p7_cpt', models.BooleanField()),
                ('p7_vcpt', models.BooleanField()),
                ('p8_pos', models.IntegerField()),
                ('p8_cpt', models.BooleanField()),
                ('p8_vcpt', models.BooleanField()),
                ('p9_pos', models.IntegerField()),
                ('p9_cpt', models.BooleanField()),
                ('p9_vcpt', models.BooleanField()),
                ('p10_pos', models.IntegerField()),
                ('p10_cpt', models.BooleanField()),
                ('p10_vcpt', models.BooleanField()),
                ('p11_pos', models.IntegerField()),
                ('p11_cpt', models.BooleanField()),
                ('p11_vcpt', models.BooleanField()),
                ('p12_pos', models.IntegerField()),
                ('p12_cpt', models.BooleanField()),
                ('p12_vcpt', models.BooleanField()),
                ('p13_pos', models.IntegerField()),
                ('p13_cpt', models.BooleanField()),
                ('p13_vcpt', models.BooleanField()),
                ('p14_pos', models.IntegerField()),
                ('p14_cpt', models.BooleanField()),
                ('p14_vcpt', models.BooleanField()),
                ('p15_pos', models.IntegerField()),
                ('p15_cpt', models.BooleanField()),
                ('p15_vcpt', models.BooleanField()),
                ('p1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick1', to='backend.player')),
                ('p10', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick10', to='backend.player')),
                ('p11', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick11', to='backend.player')),
                ('p12', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick12', to='backend.player')),
                ('p13', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick13', to='backend.player')),
                ('p14', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick14', to='backend.player')),
                ('p15', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick15', to='backend.player')),
                ('p2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick2', to='backend.player')),
                ('p3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick3', to='backend.player')),
                ('p4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick4', to='backend.player')),
                ('p5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick5', to='backend.player')),
                ('p6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick6', to='backend.player')),
                ('p7', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick7', to='backend.player')),
                ('p8', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick8', to='backend.player')),
                ('p9', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick9', to='backend.player')),
            ],
        ),
    ]
