# Generated by Django 3.2.5 on 2022-12-06 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20221206_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='player',
            name='price',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(200)]),
        ),
    ]
