# Generated by Django 3.2.5 on 2022-12-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20221206_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfplpicks',
            name='bank_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userfplpicks',
            name='team_value',
            field=models.IntegerField(default=0),
        ),
    ]
