# Generated by Django 3.2.5 on 2022-12-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20221211_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gameweek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.IntegerField()),
                ('team_a', models.CharField(max_length=30)),
                ('team_h', models.CharField(max_length=30)),
                ('team_a_difficulty', models.IntegerField()),
                ('team_h_difficulty', models.IntegerField()),
            ],
        ),
    ]
