# Generated by Django 3.2.5 on 2023-01-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20230103_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='chance_of_playing_next_round',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='news',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
